configfile: "config.yaml" 

include: "preassembly/01-fastqc.smk"
include: "preassembly/02-rcorrector.smk"
include: "preassembly/03-trimmomatic.smk"
include: "preassembly/04-kraken2.smk"

include: "assembly/01-trinity.smk"

include: "postassembly/01-rnaquast.smk"
include: "postassembly/02-busco.smk"
include: "postassembly/03-kallisto.smk"

include: "annotation/01-transdecoder.smk"
include: "annotation/02-trinotate.smk"

rule out:
    input:
        'out/trinotate/trinotate_annotation_report.xls'
    output:
        'flags/final.done'
    params:
        outputDir = config['outputDir']    
    shell:
        '''
        mv -v out/* {params.outputDir}
        '''